/*
CREAR UN PROGRAMA QUE CONTENGA:

UNA FUNCION LLAMADA COPIARVECTOR() QUE RECIBA:
DOS VECTORES
Y EL TAMANIO DE LOS MISMOS (DEBEN SER DEL MISMO TAMANIO)
Y QUE CONSIGA COPIAR EN EL SEGUNDO VECTOR EL CONTENIDO DEL PRIMERO.
*/
#include<stdio.h>
#include<stdlib.h>
#include<conio.h>
#include<string.h>

